name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT

    - name: Get release notes from commit
      id: get_notes
      run: |
        # Get the commit message for the tag
        NOTES=$(git log -1 --pretty=%B ${{ github.sha }})
        # Escape newlines for GitHub output
        NOTES="${NOTES//'%'/'%25'}"
        NOTES="${NOTES//$'\n'/'%0A'}"
        NOTES="${NOTES//$'\r'/'%0D'}"
        echo "notes=$NOTES" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        body: |
          ## Changes in this release:

          ${{ steps.get_notes.outputs.notes }}

          ### Installation
          Download the latest release and upload to your WordPress plugins directory, or use the WordPress plugin installer.

          ### Version
          **${{ steps.get_version.outputs.version }}**
        draft: false
        prerelease: false